### ISSUE TITLE
When creating a new app, port is required

### ISSUE THREAD

**Issue by natanrolnik** [qutheory/red-feedback#12]
When configuring a new app, the field _Domain Name_ has no mentions of port - but when trying to save, it requires one.
Having another field for the port (as well as explaining why it is needed) would be good.

**Comment by joscdk** [comment]
@natanrolnik the port shouldn't be required, have you made sure to install nginx .. If so and it still don't work, try clicking the Domains menu and create it from there

**Comment by joscdk** [comment]
@tanner0101 think there are a problem when creating a domain through the wizard, where it don't send the port of the application

**Comment by natanrolnik** [comment]
@joscdk I just followed the create server and create app flows, and I’m always getting the error that value for key Port is missing. 
I didn’t install ngnix - I believe this should happen “by default” when a server is created. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joscdk** [comment]
@natanrolnik it's not installed per default, because we can't know what you are going to use your server for, if you don't need nginx, it should'nt be installed :)

1. Go to tools and install Swift, Supervisor and nginx
2. Go to your app, and click Domains in the sidebar and try to create the domain again

It should work, just tried on a fresh server myself, and it worked.

**Comment by natanrolnik** [comment]
@joscdk I understand, and it makes sense. But at least a note (like what you wrote here or a link) should be there when configuring a domain, if ngnix is not installed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joscdk** [comment]
Yeah there are already a ticket for it should fail if you try to create a domain without nginx installed :)

**Comment by natanrolnik** [comment]
Oh ok :) Then I'm closing this one.
