### ISSUE TITLE
Add SSH key, misleading error message

### ISSUE THREAD

**Issue by cweinberger** [qutheory/red-feedback#13]
When creating an SSH key, I got this error message:

> **Could not create ssh-key**
> The provided key could not be validated

I used this as the name of the key: "ssh-rsa some@mail.com"

*Expected behaviour:* it should tell me that the name is not the right format.

URL: /servers/42EBBF26-528F-400C-870D-DD5CCD6E1A7A/ssh/keys/create
User ID: 703B3EEC-E6CE-4FA7-B00D-0F13C0321590
Company ID: E9C8D4A7-1FEE-4021-8BF7-BD2B7DA64103

**Comment by joscdk** [comment]
The error is now a bit more descriptive, states the key is in wrong format, and that people should upload their public key
