### ISSUE TITLE
After deleting the server, the dashboard is freezing

### ISSUE THREAD

**Issue by cweinberger** [qutheory/red-feedback#14]
I deleted the server, reloaded the page and now it keeps reloading while I cannot click anywhere.
It's using 100% cpu.

http://dashboard.vapor.red/apps

![Screenshot 2019-03-12 at 13 15 07](https://user-images.githubusercontent.com/668808/54199372-0b499e00-44c9-11e9-9aed-2c6b9f453a17.png)

Also after closing the tab and re-opening, the server is still there (but it got deleted from Digital Ocean).

What I did:
- delete app
- delete server
- => then this freeze happened

My system:
- macOS 10.14.3
- Safari Version 12.0.3 (14606.4.5)

**Comment by joscdk** [comment]
@cweinberger hmm that is strange, we will have a look .. If the server is still there, try to go in and hit delete on it again

**Comment by joscdk** [comment]
Most likely related to #15 so closing this one
