### ISSUE TITLE
Cannot delete server that is listed on Vapor RED but not on Digital Ocean

### ISSUE THREAD

**Issue by cweinberger** [qutheory/red-feedback#15]
While doing the steps described in #14, my server got deleted on Digital Ocean.
However, on Vapor Red the server is still listed and if I try to destroy it I get a "Destroy Server Failed. Something went wrong" error message.

Vapor Red:
![Screenshot 2019-03-12 at 13 23 01](https://user-images.githubusercontent.com/668808/54199790-13560d80-44ca-11e9-918b-16e12200ef7b.png)

Digital Ocean:
![Screenshot 2019-03-12 at 13 23 56](https://user-images.githubusercontent.com/668808/54199808-210b9300-44ca-11e9-97c2-e20177713895.png)

**Comment by joscdk** [comment]
@cweinberger can you try giving me the server name, then i can delete it for you

**Comment by cweinberger** [comment]
@joscdk it is `vaporred-test-01`

**Comment by joscdk** [comment]
It's deleted now, i will have a look and see if i can reproduce this .. We are however working on a large update to server delete, to make it more stable .. (Mainly because AWS delete is really annoying, and require a lot more complex system :D )

**Comment by joscdk** [comment]
There is now a PR up to solve the issues related to server deletion. However it won't be pushed until AWS is ready

**Comment by joscdk** [comment]
This should be solved now with the release of Red Alpha.2
