### ISSUE TITLE
Complaints about lacking github credentials after changing target branch

### ISSUE THREAD

**Issue by twof** [qutheory/red-feedback#16]
Changed the branch to pull from under App -> Settings -> Deploy script
Updated
Deployed

Expected behavior: Should pull from the specified branch and deploy successfully
Actual behavior: 
<img width="1224" alt="Screen Shot 2019-03-14 at 12 41 19 AM" src="https://user-images.githubusercontent.com/5561501/54339506-44316200-45f2-11e9-84ff-9a877a31415f.png">

URL: /apps/026C24E7-83B0-4745-8DB2-3800569C1EB0/settings
User ID: 7734849F-C5D2-454C-B00E-9564E95AD3C0
Company ID: 198CF095-A53C-4515-8DE0-264F8932D346

**Comment by joscdk** [comment]
I have no idea why git want the email/name, but unfortunately not really something we can do anything about.
To fix this, simply SSH into the server, and run the two commands it gives you, then it should work :)

**Comment by twof** [comment]
<img width="1029" alt="Screen Shot 2019-03-14 at 3 47 40 AM" src="https://user-images.githubusercontent.com/5561501/54351104-004b5680-460c-11e9-99d3-fad4b612a6ba.png">
Looks like it's running into conflicts because it's merging rather than checking out the new branch.

**Comment by joscdk** [comment]
Yeah it's because it runs `git pull` so you can either add a checkout to the deploy script, or delete the project folder and then deploy again.
We should maybe look into what we can do to optimise the default deploy script
