### ISSUE TITLE
App name format should be more clear

### ISSUE THREAD

**Issue by ScottRobbins** [qutheory/red-feedback#20]
For the app name I just typed "Blog", which was not in the correct format. I think that the site could probably do a better job of either not letting me enter things in an incorrect format (down-casing all letters and adding dashes instead of spaces) or giving a more descriptive error message than it currently does.

**Comment by joscdk** [comment]
@ScottRobbins i fully agree with you here. However we should maybe allow capitalized letters, since it's not for a domain, but for a folder.

I will update the error message, and allow underscore, dash, lower/capitalized letters and numbers :)

Thank you for reporting this.

**Comment by joscdk** [comment]
We have allowed for more characters in app name, and made the error a bit more clear :)
