### ISSUE TITLE
Initial flow when adding domain

### ISSUE THREAD

**Issue by ScottRobbins** [qutheory/red-feedback#22]
The initial flow of adding a new app led me to adding a domain name.

When I was going to add the domain name, initially I pressed "Skip" that button didn't seem to do anything. 

Then I went to add a domain name it errored and told me to install NGINX first, but didn't provide information how to do that. I found it under the "Domains" tab but the initial setup flow could be a little more clear how to do that.

**Comment by joscdk** [comment]
We have added some additional information regarding domain
