### ISSUE TITLE
Make sure tools can't be created in parallel

### ISSUE THREAD

**Issue by loganwright** [qutheory/red-feedback#23]
jonas mentioned it's an apt limitation to run parallel commands, maybe we can restrict in dashboard.

Expected behavior: Prevent me from installing two tools at once
Actual behavior: allows 
URL: /servers/5BA799BD-5678-4CAF-AC55-26797E5DA9DD/tools
User ID: 2699C4B2-5DF9-4547-A384-5E19B06E1EE2
Company ID: 1990EE57-9C34-4484-A096-9121B99D831F

**Comment by joscdk** [comment]
@loganwright it should already be restricted so you can't install two tools at once.. However i will make a fallback check in the API just to be safe :)

**Comment by joscdk** [comment]
However if a tool fails installing, you will get an Email specifying the error, so if you end up installing two tools at once, and one fails, the worst thing that happens is you need to click install at one of them again :)
