### ISSUE TITLE
Dismiss feedback banner

### ISSUE THREAD

**Issue by LinusGeffarth** [qutheory/red-feedback#25]
Let us please dismiss the feedback bar. It feels like the cookie banners and I just want to dismiss it 😄

**Comment by joscdk** [comment]
Could be cool to be able to "hide" it, and then have a small button to show it again, i will look into it when i have a little extra time :)

**Comment by joscdk** [comment]
After some internal talk, we aren't going to do anything about this, there are some features we rather want added.
The bar will be removed when we have the support ticket system up and running, which will be free for everyone during the beta.

After this we will see if we can integrate some kind of feedback system for people not in a plan giving access to priority support :)
