### ISSUE TITLE
dashboard feedback

### ISSUE THREAD

**Issue by byMohamedali** [qutheory/red-feedback#27]
Expected behavior:
Actual behavior:
URL: /servers/8E29DB41-B8AE-4BCF-B8B4-97D8AFF3E874/settings
User ID: B5979B82-9853-47B5-AAFA-DB66F0A55329
Company ID: F05B9D1E-C1C8-4D2C-83E8-135FE3AC034D

Hi, 

Thanks for your great product, I would like to know if there is any option to scale up my server if I need it, I choose the cheapest server but if my app grow up and I need more it's possible to scale up without destroy the server, through vapor.red ? 

Thank you

**Comment by joscdk** [comment]
@TonyStarkk You can login to the Digital Ocean dashboard and scale the server up at anytime.

We would love to add this feature to the Red dashboard at some point, and is on our list. But until you can easily do it through DO :)
