### ISSUE TITLE
HTML Issue with Credentials select

### ISSUE THREAD

**Issue by InukVT** [qutheory/red-feedback#28]
Expected behavior:
Being able to create a server with DO
Actual behavior:
![image](https://user-images.githubusercontent.com/7114643/57366365-1c402400-7187-11e9-9710-0a101eeb480c.png)

The creds are RIGHT as far as I'm aware, I copied creds from DO using their clipboard tool.
URL: /servers/create
User ID: 79F1FD59-84E1-410B-ABEC-04ECD05B7CAF
Company ID: 6681451F-C5C8-4948-BF41-12D97B82AB00

![image](https://user-images.githubusercontent.com/7114643/57366340-10ecf880-7187-11e9-9c98-614f1a7defb3.png)

**Comment by joscdk** [comment]
@tanner0101 can you take a look at this?

**Comment by joscdk** [comment]
I haven't been able to reproduce this since.
