### ISSUE TITLE
Allow for deleting firewall rule

### ISSUE THREAD

**Issue by siemensikkema** [qutheory/red-feedback#30]
Expected behavior: I should be able to remove or edit Firewall rule
Actual behavior: I see no way to do this, I can only add rules
URL: /servers/A597A9CD-D2FC-4132-9CAB-D1DC54AD12FB/network
User ID: 5BCDBFAD-04D7-4A9E-A31E-63D8831240C9
Company ID: 4DD741C7-58AB-4F16-A2CF-FE33E2729C0A

**Comment by joscdk** [comment]
Hmm i can see we never got that added in the dashboard. I will look into this ASAP.

In the beginning we will have delete, but not edit, edit will come later :)

**Comment by joscdk** [comment]
@siemensikkema it's now possible to delete a firewall rule.
