### ISSUE TITLE
Deployment can fail without reporting status back to the dashboard

### ISSUE THREAD

**Issue by siemensikkema** [qutheory/red-feedback#32]
Expected behavior: Deployment is marked as failed when there is an issue with the environment variables. (I got this error `ERROR: CANT_REREAD: Unexpected end of key/value pairs in value` possibly because of a missing newline at the end).
Actual behavior: Deploy seems to be still in progress with no way to cancel it
URL: /apps/1FE3E69D-7250-48D7-AFE8-A19BEC6E05C7/deploy
User ID: 5BCDBFAD-04D7-4A9E-A31E-63D8831240C9
Company ID: 4DD741C7-58AB-4F16-A2CF-FE33E2729C0A

**Comment by siemensikkema** [comment]
It doesn't seem to be related to a newline but to how the environment variables get stored in the supervisor config file. Instead of environment=A="VALUE_A",B="VALUE_B" it is written as a single key value pair per newline. Because of this supervisor complains and the deployment never finishes so I have to delete and recreate the app.

**Comment by siemensikkema** [comment]
Oh I just found out I can trigger a deployment through the url so I don't have to delete my app anymore although now there are multiple deployments "running"

**Comment by siemensikkema** [comment]
Another update. Newlines are ok but supervisor just needs `"` around each value. If I edit the config file myself and run `supervisord -n` I can see it accepts the configuration. However, a new deployment on Vapor RED overwrites the config causing it to fail again.

**Comment by joscdk** [comment]
@siemensikkema yeah, currently the way it adds the config through the bash script is a bit annoying.

You can get around it by adding your env vars like:

```
MY_VAR='MY_KEY'
```
(Using Single quotes), this works fine. I hope in the next update to get it solved so it's possible to use double quotes :) .. I will get the running deployments stopped :)

**Comment by joscdk** [comment]
@siemensikkema for now, i have added an INFO box in the Environment box, so it should be easier to spot :) 
![image](https://user-images.githubusercontent.com/2535140/57989314-36d4a000-7a99-11e9-8aeb-a37cbecd24c5.png)

**Comment by joscdk** [comment]
It seem to fail the deploy correctly now if something goes wrong with the Supervisor configuration
