### ISSUE TITLE
Server Provisioned Email

### ISSUE THREAD

**Issue by OurBigAdventure** [qutheory/red-feedback#33]
I'm stuck after receiving the 'Server Provisioned' email for an AWS instance.  I've added my SSH key to the AWS User with no success.  I've followed the QuickStart including the AWS specific instructions and can't seem to understand what to do with my SSH key.  If you can't build in a field to set the SSH key on the VPC for me could you maybe describe the steps required more throughly in the documentation?

**Comment by joscdk** [comment]
@OurBigAdventure just to understand, you are trying to access your server through SSH? if so, click the server in the Red dashboard, and click "SSH" here upload your SSH public key, after which you should be able to ssh with:
```
ssh red@<server-ip>
```

We will soon start focusing on getting more documentation up, including recorded videos showing various features, to make it easier getting started.

**Comment by OurBigAdventure** [comment]
After trying a few other server setups I realized that the email specifies adding my public key to the Vapor.red dashboard.  I began hunting and found the '+' under the SSH info.  Now that I know what to do it's easy, but maybe a little more clarity in the intro email would cut support requests in the future?

I like the idea of the videos, much easier to follow something like that.

**Comment by joscdk** [comment]
Yeah that make sense, i will try to go through the Email, and make sure the text is more clear.

Thanks for the feedback :)
