### ISSUE TITLE
dashboard feedback

### ISSUE THREAD

**Issue by OurBigAdventure** [qutheory/red-feedback#34]
I have a stuck DigitalOcean server.  I tried creating it about two days ago and it still says creating with no way to cancel or delete.  I have since created another that is working fine.

**Comment by joscdk** [comment]
@OurBigAdventure yeah we had some problems with the background queues used to create servers. We will be removing these servers that are stalled, but if you want it gone before, give me the name, and i can delete it for you :)

**Comment by OurBigAdventure** [comment]
Not a big deal I just wanted to report incase it wasn't a known issue
