### ISSUE TITLE
Can't skip 'Configure Domain' in App creation

### ISSUE THREAD

**Issue by OurBigAdventure** [qutheory/red-feedback#35]
Expected behavior: Clicking 'Skip' allows app creation to continue without a domain name
Actual behavior: Nothing happens
URL: /apps/6C5E4A1E-2735-4C84-B8B9-568BD928DBEF/bootstrap/domains
User ID: E932C3FF-D7C9-43D5-A5A8-EC60BFFA0E7C
Company ID: 424BB2D9-79AC-4110-9E83-50B95AF9C8EF

**Comment by joscdk** [comment]
Thanks for reporting this, we will take a look at this asap :)

**Comment by joscdk** [comment]
We have removed this step for now.
