### ISSUE TITLE
Installing nginx failed

### ISSUE THREAD

**Issue by rminerick** [qutheory/red-feedback#37]
Expected behavior: Installing nginx installs nginx.
Actual behavior: I gen an email that installing nginx failed, here is the output in the attachment to the email:

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Ign:2 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu bionic InRelease
Err:4 https://repos.insights.digitalocean.com/apt/do-agent main Release
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 104.16.182.15 443]
Hit:5 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease
Hit:6 http://ppa.launchpad.net/nginx/development/ubuntu bionic InRelease
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:8 http://mirrors.digitalocean.com/ubuntu bionic-backports InRelease
Reading package lists...
E: The repository 'https://repos.insights.digitalocean.com/apt/do-agent main Release' no longer has a Release file.

URL: /servers/D7F29FD7-1CB0-436A-9BF3-CE1A7D764A6B/tools
User ID: 991E4A40-24FE-43A5-BCF3-1174A08650E7
Company ID: B4911E97-CB92-403B-9CAC-96AE604E016A

**Comment by joscdk** [comment]
@rminerick you closed the issue, did you find a solution or?

**Comment by rminerick** [comment]
No - sorry, wanted to check and ensure I wasn't missing something before I left an open issue. I don't think I am, still can't get nginx installed :(

**Comment by joscdk** [comment]
@rminerick looks like a problem at Digital Ocean, i will keep monitoring it, and will report back when it works :)

**Comment by rminerick** [comment]
Sounds good - thanks!

**Comment by rminerick** [comment]
Looks like it's been resolved. Thanks!

**Comment by joscdk** [comment]
It looks to be going up and down, still don't work on my test server, i will keep monitoring it :) .. But glad it works for you now, that's the important part :)
