### ISSUE TITLE
dashboard feedback

### ISSUE THREAD

**Issue by SmartJSONEditor** [qutheory/red-feedback#38]
Expected behavior:
Actual behavior:
URL: /servers
User ID: BD342461-DE1C-4D52-8A86-1AA1381A3AD7
Company ID: 2993A68B-A922-49CD-A98C-388424AA2B57

I am unable to remove or disable my project that is in creating state forever.
My server is in creating status and I am unable to delete it or do something.

**Comment by joscdk** [comment]
@SmartJSONEditor is it application or server?
