### ISSUE TITLE
Red attempts to create domains anyway upon failure

### ISSUE THREAD

**Issue by twof** [qutheory/red-feedback#4]
Repro steps:
Don't install NGINX on your server
Create an app
When you get to the step to enter a domain name, enter your domain and you'll get an error
After installing NGINX, you'll see that Red is trying to create any domains that errored out
<img width="1211" alt="Screen Shot 2019-03-11 at 1 06 17 PM" src="https://user-images.githubusercontent.com/5561501/54154382-06b8b300-43ff-11e9-8fd4-16de9757550e.png">

**Comment by joscdk** [comment]
Thank you for this, we will have a look :)

**Comment by joscdk** [comment]
Nginx is now required on the server before you can create your domain. We have also made a validation, so you can only create the same domain once (You can still create different subdomains)
