### ISSUE TITLE
Enabling TLS (Let's Encrypt) fails if ports 80 and 443 are not open

### ISSUE THREAD

**Issue by siemensikkema** [qutheory/red-feedback#47]
When enabling TLS (Let's Encrypt) on a domain before having opened port 80 and 443 on the server fails. There is no error information under the failed Provision.

I would expect either of these things to happen:
- an error message describing why TLS could not be configured after it fails
- or even better: a warning above the "Configure TLS" button saying the ports are not opened (and possibly not allowing me to perform the action)

**Comment by joscdk** [comment]
![network_fail](https://user-images.githubusercontent.com/2535140/63338332-df1d2d80-c342-11e9-8f3a-1ea46813a22a.png)

Thursday we will push an update that will show an error if you don't have port 80 and 443 open in the firewall when provisioning TLS :) .. That's at least a start
