### ISSUE TITLE
Connection closed to deployment logs upon deploy

### ISSUE THREAD

**Issue by twof** [qutheory/red-feedback#5]
<img width="1060" alt="Screen Shot 2019-03-11 at 1 14 12 PM" src="https://user-images.githubusercontent.com/5561501/54154732-d58cb280-43ff-11e9-8724-7f26b965c611.png">

After refreshing the page, it attempts to connect to deployment logs again, this time successfully.

**Comment by joscdk** [comment]
Yeah it's currently on the roadmap to make some optimisations for the deploy logs when it opens, we have seen a couple of different bugs with it unfortunately.

**Comment by joscdk** [comment]
It should be a bit more stable now.
