### ISSUE TITLE
Server stuck as 'Creating'

### ISSUE THREAD

**Issue by OurBigAdventure** [qutheory/red-feedback#54]
Expected behavior: I expected that the stalled server creation would be removed by now.
Actual behavior: it still exists
URL: /support
User ID: E932C3FF-D7C9-43D5-A5A8-EC60BFFA0E7C
Company ID: 424BB2D9-79AC-4110-9E83-50B95AF9C8EF
version: 1.1.3

**Comment by joscdk** [comment]
@OurBigAdventure sorry for the troubles, there are unfortunately still API errors from some providers we haven't been able to catch yet.
I have deleted the server for you now.
