### ISSUE TITLE
Change git branch of app

### ISSUE THREAD

**Issue by hishma** [qutheory/red-feedback#55]
Expected behavior:

I'd like to be able change the git branch of an app.

Actual behavior:

It's not possible. Though I can edit the deploy script as a work around.

URL: /support
User ID: A68BCCC8-EB97-413D-B2C7-08AED69A55BF
Company ID: 20F963B6-8F78-4550-A074-55608E65B49D
version: 1.1.3

**Comment by joscdk** [comment]
It was solved with the new release last night, it can now be changed from `Settings`
