### ISSUE TITLE
dashboard feedback

### ISSUE THREAD

**Issue by jhhenriksen** [qutheory/red-feedback#56]
Expected behavior: I want to be able to remove two AWS servers during the "creating" stage.
![Skärmavbild 2019-10-05 kl  19 29 39](https://user-images.githubusercontent.com/6330075/66258580-38cca080-e7a7-11e9-9502-6b51c11e95db.png
I also want to remove my AWS Cloud Provider account - but it is locked.
![Skärmavbild 2019-10-05 kl  19 29 39](https://user-images.githubusercontent.com/6330075/66258589-5863c900-e7a7-11e9-93b2-b00b25f24d43.png)
)

Actual behavior: "Server not ready yet" - it will never be because I have changed from AWS to Linode
URL: /support
User ID: 425EA6CA-F72A-4C27-A691-BF9B84CC8D70
Company ID: D54F9DA8-EAC9-4E21-B738-391E69C7CDFB
version: 1.1.3

Please remove the two AWS servers on this account.

Best
Jan-Helge Henriksen
jh@sequense.se
Sweden

**Comment by joscdk** [comment]
Hi @jhhenriksen sorry for the troubles, i have deleted them for you now. We have put in some safe-guards for AWS, that should catch most errors we get from the AWS API.

**Comment by jhhenriksen** [comment]
Thanks! Very good - looks nice and tidy now :)
Jan-Helge
