### ISSUE TITLE
It's unclear that something more has to be done in order to rig up a domain to your app

### ISSUE THREAD

**Issue by twof** [qutheory/red-feedback#7]

**Comment by joscdk** [comment]
Yeah aside from a page in the documentation, we should properly have a note in the dashboard, informing people to setup DNS for their domain

**Comment by joscdk** [comment]
It's now in the documentation stating people need to add an A record https://docs.vapor.red/application/setup-domain/

**Comment by joscdk** [comment]
We have now also added some information boxes in the domain setup process.
