### ISSUE TITLE
Database doesn't list port that it's running on

### ISSUE THREAD

**Issue by twof** [qutheory/red-feedback#9]
Expected behavior: dashboard should tell users the port that databases are serving from
Actual behavior: doesn't do that

URL: /servers/6F0D361B-627B-4BD1-8807-0F8F21951A18/database-servers/CA308718-EF76-4451-9C73-F9E5EFCC6297
User ID: 7734849F-C5D2-454C-B00E-9564E95AD3C0
Company ID: 198CF095-A53C-4515-8DE0-264F8932D346

Would also be good if there was some means of adding DB information to an app's env variables automatically

**Comment by joscdk** [comment]
@tanner0101 we should maybe just hardcode the port for psql and mysql .. We should also add a way to see connect details

**Comment by tanner0101** [comment]
Done: 

![Screen Shot 2019-03-14 at 4 59 01 PM](https://user-images.githubusercontent.com/1342803/54391181-869e8180-467a-11e9-9c05-21c461f0b74b.png)
